# Generated by Django 5.2.3 on 2025-07-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='The full API endpoint URL, e.g., /api/login/', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of what this API does.', null=True)),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Last time this API was successfully accessed.', null=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this API has been accessed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Endpoint',
                'verbose_name_plural': 'API Endpoints',
                'ordering': ['endpoint'],
            },
        ),
    ]
