# Generated by Django 5.2.3 on 2025-07-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The text displayed in the navigation bar.', max_length=100)),
                ('url', models.CharField(blank=True, help_text='The URL this menu item links to. Leave blank for parent items that only serve as dropdowns.', max_length=200, null=True)),
                ('order', models.IntegerField(default=0, help_text='The order in which menu items appear (lower numbers first).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this menu item should be displayed.')),
                ('parent', models.ForeignKey(blank=True, help_text='Select a parent menu item if this is a sub-menu item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='PetStore.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['parent__order', 'order', 'title'],
            },
        ),
    ]
