# Generated by Django 5.2.3 on 2025-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload the image for this slide.', upload_to='slides/')),
                ('tagline', models.CharField(help_text="The small paragraph text (e.g., 'Premium pet supplies for happy tails').", max_length=200)),
                ('heading', models.CharField(help_text="The large heading text (e.g., 'Pet Shop').", max_length=150)),
                ('button_text', models.CharField(default='Shop Now', help_text='Text for the call-to-action button.', max_length=50)),
                ('button_url', models.CharField(default='#', help_text="The URL the button links to (e.g., '/shop/').", max_length=255)),
                ('order', models.IntegerField(default=0, help_text='The display order of the slide (lower numbers first).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide should be displayed in the slideshow.')),
            ],
            options={
                'verbose_name': 'Slideshow Slide',
                'verbose_name_plural': 'Slideshow Slides',
                'ordering': ['order'],
            },
        ),
    ]
