# Generated by Django 5.2.3 on 2025-07-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetStore', '0002_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the category (e.g., 'Pet foods', 'Dogs').", max_length=100)),
                ('url', models.CharField(blank=True, help_text="The URL this category links to (e.g., '/shop/pet-foods/'). Leave blank for parent categories that only serve as headers for collapsible menus.", max_length=200, null=True)),
                ('icon_id', models.CharField(blank=True, help_text="The ID of the SVG symbol to use for this category (e.g., 'dairy', 'meat', 'health').", max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='The order in which categories appear (lower numbers first).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category should be displayed.')),
                ('parent', models.ForeignKey(blank=True, help_text="Select a parent category if this is a sub-category (e.g., 'Dogs' under 'Health products').", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='PetStore.category')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['parent__order', 'order', 'name'],
            },
        ),
    ]
