# Generated by Django 5.2.3 on 2025-07-19 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetStore', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product.', max_length=200)),
                ('image', models.ImageField(help_text='Main image for the product.', upload_to='products/')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price of the product.', max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price of the product (optional).', max_digits=10, null=True)),
                ('slug', models.SlugField(blank=True, help_text='A short, unique label for the product URL (auto-generated if left blank).', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product.')),
                ('stock', models.IntegerField(default=0, help_text='Current stock quantity.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is available for sale.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='The category this product belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='PetStore.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
