# Generated by Django 5.2.3 on 2025-07-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetStore', '0013_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
